env: "dev" # dev/pro/test

database:
  db_name: "database"
  username: "username"
  password: "password"
  address: "localhost:3306"

server:
  port: "8888"
  allow_origins:
    - "localhost:8080"

file:
  auto_path: "./upload"
  manual_path: "./file"
  
jwt:
  secret: "secret"
  issuser: "someone"
  expires: 48 # hours

